### PR TITLE
Add spotify APP

### PR DESCRIPTION
**Pull request by alefnode**
Add new APP for spotify third party apps permissions

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Thank you!

**Comment by bilelmoussaoui** [comment]
I just noticed the url points to /es locale, I think the user will be redirected to the right page depending on the default language later. We can't do much about it from our side I guess? or maybe default to english?

**Comment by alefnode** [comment]
Just modified here

https://github.com/bilelmoussaoui/revoke.app/pull/5

Tested, seems to works well

**Comment by bilelmoussaoui** [comment]
Thanks for the fast response & fix :)

**Pull request merged**
